# 這是 PostgreSQL Replica 節點的 Ansible 任務檔案
- name: 設定正確的資料目錄變數（跨平台）
  ansible.builtin.set_fact:
    postgresql_data_dir: >-
      {{
        (postgresql_data_dir_redhat | default('/var/lib/pgsql/17/data')) if ansible_facts['os_family'] == 'RedHat'
        else (postgresql_data_dir_debian | default('/var/lib/postgresql/17/main'))
      }}

# ✅ RedHat 系列處理
- name: 安裝 PostgreSQL 17（RedHat）
  when: ansible_facts['os_family'] == "RedHat"
  block:
    - name: 加入 PostgreSQL Yum Repo
      ansible.builtin.get_url:
        url: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        dest: /tmp/pgdg-redhat-repo.rpm
        mode: '0644'

    - name: 安裝 Yum Repo
      ansible.builtin.yum:
        name: /tmp/pgdg-redhat-repo.rpm
        state: present

    - name: 禁用內建 PostgreSQL 模組
      ansible.builtin.command: dnf -qy module disable postgresql
      args:
        creates: /etc/dnf/modules.d/postgresql.module
      changed_when: false

    - name: 安裝 PostgreSQL
      ansible.builtin.yum:
        name:
          - postgresql17-server
          - postgresql17
        state: present

# ✅ Debian/Ubuntu 系列處理
- name: 安裝 PostgreSQL 17（Debian/Ubuntu）
  when: ansible_facts['os_family'] == "Debian"
  block:

- name: 建立 keyrings 資料夾（如未存在）
  ansible.builtin.file:
  path: /etc/apt/keyrings
  state: directory
  mode: '0755'

- name: 移除舊的 PostgreSQL APT Repository（若存在）
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.apt_repository:
  repo: "deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
  filename: pgdg
  state: absent

- name: 下載 PostgreSQL GPG 金鑰（.asc）
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/keyrings/postgresql.asc
    mode: '0644'

- name: 將金鑰轉為 binary keyring
  ansible.builtin.shell: |
    set -euo pipefail
    gpg --dearmor /etc/apt/keyrings/postgresql.asc -o /etc/apt/keyrings/postgresql.gpg
  args:
    creates: /etc/apt/keyrings/postgresql.gpg

- name: 加入 PostgreSQL APT Repo（Ubuntu 22+ 包含 Noble）
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/postgresql.gpg arch=amd64] https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    filename: pgdg
    state: present
    update_cache: true

- name: 安裝 PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql-17
    state: present

# ✅ 共通步驟
- name: 部署 postgresql.conf（readonly 可選）
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_data_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL

- name: 部署 pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_data_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: '0600'
  notify: Reload PostgreSQL

- name: 啟動 PostgreSQL 服務
  ansible.builtin.service:
    name: postgresql-17
    state: started
    enabled: true

- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql-17
    state: restarted

- name: Reload PostgreSQL
  ansible.builtin.systemd:
    name: postgresql-17
    state: reloaded
