---
- name: 推送 SSH 金鑰到 PostgreSQL 節點
  hosts: postgresql
  gather_facts: false
  become: false
  vars:
    ssh_user: postgres  # 可由 CLI 覆蓋：--extra-vars "ssh_user=root"

  tasks:
    - name: 確保每台主機加入 known_hosts（避免卡 yes/no）
      delegate_to: localhost
      run_once: false
      ansible.builtin.shell: |
        ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
      changed_when: false

    - name: 傳送 ssh_push.sh 腳本
      ansible.builtin.copy:
        src: tools/ssh_push.sh
        dest: /tmp/ssh_push.sh
        mode: '0755'

    - name: 執行 ssh_push.sh 腳本（推送金鑰）
      ansible.builtin.shell: "/tmp/ssh_push.sh {{ ssh_user }}"
      args:
        executable: /bin/bash
