---
- name: 初次推送 Root 的 SSH 公鑰到所有主機（由控制端執行）
  hosts: 192.168.25.115,192.168.25.116,192.168.25.117
  gather_facts: false
  become: false

  vars:
    ssh_pubkey_path: "~/.ssh/id_rsa.pub"

  tasks:
    - name: 確認本地 SSH 公鑰是否存在
      delegate_to: localhost
      stat:
        path: "{{ ssh_pubkey_path }}"
      register: ssh_key_check

    - name: 終止：若找不到 SSH 公鑰，提示使用者先產生
      delegate_to: localhost
      fail:
        msg: |
          ❌ 找不到 {{ ssh_pubkey_path }}
          請先執行 ssh-keygen 建立金鑰： ssh-keygen -t rsa -b 4096
      when: not ssh_key_check.stat.exists

    - name: 從控制端讀取本機 SSH 公鑰內容
      delegate_to: localhost
      slurp:
        src: "{{ ssh_pubkey_path }}"
      register: ssh_pubkey_data

    - name: 將控制端的 SSH 公鑰推送到遠端 root 帳號的 authorized_keys
      ansible.builtin.authorized_key:
        user: root
        state: present
        key: "{{ ssh_pubkey_data.content | b64decode }}"
